---
title: "Minutes 2021-05-07"
author: Joseph Rickert
date: 05-07-2021
---

::: {.callout-tip collapse="true"}
## View Attendee List

- "Bryant Chen - FDA"
- "Bob Engle"
- "Steven Hasendinckx J&J"
- "Doug Kelkhoff - Genentech"
- "Ning Leng - Genentech"
- "Eric Nantz - Lilly"
- "Joseph Rickert - R Consortium"
- "Paul Schuette - FDA"
- "Mike Stackhouse - Atorus Research"
- "Adrian Waddell - Roche"
- "Nan Xiao - Merck"
- "Yilong Zhang - Merck"
:::

### Recording

The meeting was recorded and the video is available at the link given below. Time stamps in the Minutes refer to the video.

### Minutes

Joseph Rickert opened the meeting at 9AM Pacific Time and told the group that Mike Stackhouse has revised the [document for a pilot submission](https://github.com/RConsortium/submissions-wg/blob/main/Documents/pilot_submission_proposal.Rmd) which is in the document folder of the GitHub repo. He asked Mike to give an overview.

**1:10** Mike's Overview:
The Submissions Working Group should make the opportunity to test out the [pkglite](https://merck.github.io/pkglite/) package and try to get a pilot submission through the [eCTD](https://www.fda.gov/drugs/electronic-regulatory-submission-and-review/electronic-common-technical-document-ectd) gateway. The objective would be to determine if an FDA reviewer would be able to receive and consume the content. This effort would be a discovery process exposing unanticipated problems in getting an R submission through the gateway and help to identify difficulties an FDA consumer would have in replicating the outputs of the pilot.

Mike stated that having a concrete example of pushing an R submission through the gateway would be "momentous". 

**6:37** Joe asks Paul Schuette if he agrees with Mike's assessment of the benefits of the pilot. Paul affirms that it would be helpful and suggest using a simulated data set.

**7:55** Joe asks Paul if special preparation would have to happen on the receiving side. Paul replies that it would depend on the processes and procedures of gateway, and notes that in the past the authorities have asked for submissions by DVD and mail (This came up last year with respect to submitting University COVID tests.)

**11:03** Paul recommends putting in a formal request to involve additional agency reviewers. Mike suggests that submitting through Phuse would have some advantages since Phuse has a structured relationship with the FDA.

**12:53** Based on previous experience, Paul states that his is not certain about the efficacy of the Phuse relationship, but that he does not have serious objections

**15:06** Paul raises the possibility that the R Consortium could sponsor the pilot. Doug Kelkhoff, Yilong Zhang and others endorse this idea.

Adrian Waddell asks how difficult is it to make a submission? Paul replies that he is not sure, but adds that to his knowledge at least one foundation has made a submission in the past. He advises we would have to reach out to group that manages gateway and EDR, and remarks that the R Consortium may have resource issues that pharma company does not have.

**17:37** Adrian alternative: 

* Split out the data and analysis code which need to be secure and go through gateway process. 
* Put the code that does not involve patient level data on a public Github repository and devise a secure way to give the agency access. 

**19:35** Paul describes a similar process he and Eric went through with a Lilly pilot where Paul had access to a Lilly Github site for 8 hours. This was a process that agency was able to handle with Eric's help, but it was a one-off effort as part of [CID pilot](https://www.clinicaltrialsarena.com/news/lilly-pain-trial-protocol/) and not a typical submission. He speculates that the process would probably not be allowed as part of standard submission package. 

**26:09** Mike brings the conversation back to logistics of getting a submission number to get the pilot process started.

**27:24** Joe asks if it is possible for more than one company to make joint submission and Doug clarifies this to mean have multiple companies co-sponsor a submission. He that the word "Sponsor" has a technical meaning to the FDA and that the system is set up for sponsors to be a company. The group agrees that the ideal would be to have R Consortium be the surrogate sponsor of the pilot.

**28:48** Paul suggests that we assess the possibility of having the R Consortium sponsor by reaching out to [Ethan Chen](https://www.linkedin.com/in/ethan-chen-6b6918b/) who heads up the Division of Data Management Services and Solutions. Doug suggests that we invite Ethan, or someone designated by him to our next meeting.

Paul notes that the invitation should be a formal process and suggests that as the representative of the R Consortium Joe write to Ethan to ask his group to participate in the process of planning for a pilot submission. Paul suggests that the letter could reference him and that the content of the letter emphasize that our group is part of an industry effort to help 
enhance and modernize submission tools. We are independent of, but in line with the recent Transcelerate [MSA framework](https://www.transceleratebiopharmainc.com/wp-content/uploads/2021/04/MoA-Initiative_MSAFramework_April-2021.pdf) and the work being done by the R Validation Hub. Both of these efforts provide some justification as to why companies and consortia are interested the submissions process.

**34:37** Joe agrees write the email letter. Doug, Eric and other agree to help with drafting it.

**40:40** a discussion about whether approvals need to be obtained from the individual pharmaceutical companies

Adrian points out that we would want to be able to try multiple approaches, and Paul indicates that an advantage of having the R Consortium sponsor would be to have multiple updates on the same submission number. It can sometimes take some companies multiple efforts to get something through the gateway

**46:53**  Adrian asks when we make a solution how does the analysis code access the data? Paul replies that the standard is to have an M5 folder to hold CDISC tabular data and analysis data - code can be in separate folder or along with analysis data sets.

**51:00** Adrian describes the main goal to give health authorities something that they can easily use themselves.

**51:30** states the measure of success :
Deliver something like like the  CDISC package through eTCD and have and FDA reviewer recreate and install packages and reproduce the results

**54:41** Doug advises that the letter be general with no technical detail stating the R Consortium's interest in being a sponsor and asking for agency participation.

**Action item**
Joe to draft letter and place it in the documents folder of the submissions repo by Tuesday of next week. The team will review and comment.

The video recording of the meeting is available [here](https://zoom.us/rec/share/0xwlkKrBNSYNY9kbv_coiyMXseSnJFaR08SVQgSDhWR20YNLbMhdpjN9dbmNLpA.Sd70XVBM34WGguwW) Passcode: `Gb#E@4$S`