---
title: "Minutes 2021-06-04"
date: 06-04-2021
---

::: {.callout-tip collapse="true"}
## View Attendee List

- "Sascha Ahrweiler - Bayer"
- "Ethan Chen - FDA"
- "Heather Crandall - FDA"
- "Bob Engle - Biogen"
- "Bella Feng -"
- "Steven Hasendinckx - J&J"
- "Chris Kania - Biogen"
- "Doug Kelkhoff - Genentech"
- "Ning Leng - Genentech"
- "Tadeusz Lewandowski - Roche"
- "Eli Miller - Atorus"
- "Eric Nantz - Lilly"
- "Joseph Rickert - R Consortium"
- "Paul Schuette - FDA"
- "Ojesh Upadhyay - GSK"
- "Adrian Waddell - Roche"
- "Nan Xiao - Merck"
- "Jiang Xu - FDA"
- "Yilong Zhang - Merck"
:::

*Note that the bold numbers in the minutes are time stamp references for the video recording.*

Joseph Rickert opened the meeting by welcoming guests from the FDA Ethan Chen, Heather Crandall and Jiang Xu and giving brief description of the R Consortium and its mission.

Joe then summarized the purpose of the meeting: the Submissions working group is working on a pilot submission to the FDA that would test whether an "all R" submission could pass the submssions process and be easily consumable by the FDA reviewers. Furthermore, the group would like to have the R Consortium act as the sponsor of the pilot submission, and is looking for guidance to determine if this is possible.

**6:31** Ethan Chen expressed a desire to support the R Consortium initiative and mentioned that R is currently included as a  supported file eCTD file format. See [Specifications for File format Types Using eCTD Specifications](https://www.fda.gov/media/85816/download).

**15:00** 
1. Test the exchange mechanism through the gateway and routing to the specific in the review division
2. Once received, can they be open and reviewed

Ethan stated that his team is involved mainly with the exchange method.

**15:30** 
In general, to initiate an a submission in a production environment an organization must open an [ESG Accoount](https://www.fda.gov/industry/electronic-submissions-gateway/create-esg-account). This process includes requesting an account and writing a [Non-Repudiation letter](https://www.fda.gov/industry/about-esg/appendix-g-letters-non-repudiation-agreement) to the FDA. (See the [AS2 Account Checklist](https://www.fda.gov/industry/create-esg-account/setting-as2-account-checklist)). The FDA then will assign an application number.

**19:32** Doug Kelkhoff asks if it is possible for a non-profit such as the R Consortium could be a sponsor. Jiang Xu believes it is possible but will require further discussion.

**22:40** Adrian Waddell describes the interplay of the exchange and review processes.

**23:00** Ethan Chen outlines two major concerns: 

1. Security (Executable files not accepted)
2. To meet the error records management requirement the FDA must be able to open any submitted file for the entire retention period which could be up to 30 years.

**26:00** Joe ask Ethan if there is someone in particular who could help setting up the ESG account. Ethan replies that Heather and Jiang could help and also help to determine if the R Consortium could be a sponsor.

**26:55** Heather Crandall recommends becoming familiar with the requirements on the [ESG Webpage](https://www.fda.gov/industry/electronic-submissions-gateway).

**28:00** Doug Kelkhoff initiates a discussion of the challenges that the working group is hoping to address.

The ask right now is for the working group to understand what steps we must undertake and who would be our FDA contact is we get stuck.

**30:15** Jiang Xu states that the FDA would want to know exactly what things we think the FDA would need to test and notes that different FDA offices and centers would need to be involved.

**34:00** Yilong Zhang points out that a goal of the working group is to test how internally R packages could be transmitted to the FDA as part of a submission.

**35:25** Doug Kelkhoff describes challenges including file extensions and case sensitivity

**36:55** Adrian Weddell notes that if the working group is able to successfully make a pilot submission and put it out in the open it would provide a guide for other companies to follow. He also raised the issue of probing the security issues around the way R packages often require dependent packages to be installed.

**40:10** Bell Feng compares an R script to a SAS macro and asks for clarification about how we are using packages. Doug Kelkhoff clarifies that the issue is about the using R best practices and being able to install packages required to perform and analysis and not just submit R scripts.

**50:00** Joe asks if there are any other FDA offices or groups that the working group should contact. Jiang and Heather do not think any other contacts are necessary to contact at this time. Jiang indicates that they will discuss this within the FDA.  

The group agreed to meet next on Wednesday June 30, 2021.

The video of the meeting is [available here](https://zoom.us/rec/share/PebMydo92bEAzQ8-l9n0D4ZPgtczBc6nBkqSpo4erSx8Z_n647nvzz76cp8NANZs.GJIbUFTJUC-UdXSB) Passcode: `V@.?eq85`

**Action Items for the Working Group**  

1. Generate a list of potential issues and items that we think the FDA will want to evaluate.
2. Become familiar with process and requirements for opening an ESG account as described on the [Electronic Submissions Gateway](https://www.fda.gov/industry/electronic-submissions-gateway) site.
