---
title: "Minutes 2024-08-02"
author: Joseph Rickert
date: 2024-08-02
---

::: {.callout-tip collapse="true"}
## View Attendee List

-   Andre Couturier (Sanofi)
-   Eric Nantz (Eli Lilly)
-   Heidi Curinckx (Johnson & Johnson)
-   HyeSoo Cho (FDA)
-   Jizu Zhi (FDA)
-   Joseph Rickert (R Consortium)
-   Michael Kane
-   Nan Xiao (Merck)
-   Ning Leng (Roche/Genentech)
-   Paul Schuette (FDA)
-   rzhang (J&J)
-   Robert Devine (Johnson & Johnson)
-   Sam Parmar (Pfizer)
:::

The meeting was recorded and the [video](https://zoom.us/rec/share/q1OxNGNb9yLXC8l5xAPyAdiIz9qBc5GG45Br9dVPvJAVrfpuiKWQSuNIY0QQpGSR.1wBN0XjiXC3BIVeb?startTime=1722614682000) is available.

## Pilot 3

Hye Soo reported that the Pilot 3 review has not yet been completed by he FDA authorities. There are no known problems. The delay is most likely due to a summer slowdown.

Before the meeting Joel Laxamana shared a list of recent and upcoming Pilot 3 related talks.

1.  [Pilot 3 Demo : R/Medicine 2024\](https://rconsortium.github.io/RMedicine_2024/Program.html)
2.  [Pilot 3 Demo : useR! 2024 On-line talk](https://www.youtube.com/watch?v=vPmNdHTVYm8&list=PL77T87Q0eoJhsC203plZ1H4p21AGrM9rl&index=12)
3.  [Roche-Genentech Coursera training on 'Hands on Clinical Reporting using R'](https://pharmaverse.github.io/blog/posts/2024-07-03_introducing_a_ne.../introducing_a_new_coursera_course_for_hands_on_clinical_data_science_using\_\_r..html)
4.  Joel will also be a part of a PHUSE WG project coming up. Yet to be started, but will share more details soon.

**Acton**: Ning will begin a draft blog post for Pilot 3 to be posted after the FDA review is complete. The post should provide context for the achievement that is helpful for making newcomers to the use of R in FDA submissions comfortable. For example, multiple R packages were deliberately used in the Pilots in order to signal that there is no one correct way to do things.


## Pilot 4

### WebAssembly 
Eric Nantz reported on a number of updates to the Pilot 4 WebAssembly submission package. 

* To take advantage of the new behavior of v0.2.0 of the Shinylive package: "...when exporting an app with the Shinylive R package, or using the Quarto extension, R packages dependencies will be frozen and bundled with your app as a private #wasm package library."
* We have been using R v4.2.3 in the Pilot 4 submission, however because WebAssembly defaults to R v4.2.1 we have switched to this version to maintain consistency. (This will be documented in the ADRG.)
* Making the change above also means that both version of running Pilot 4, i.e either as a traditional Shiny app or a precompiled wasm bundle, will use the same versions of R packages.
* The new version of the Shinylive app with WebAssembly has reduced the start up time for the Pilot 4 submissions package from over a minute to 15 seconds.
* We will schedule Pilot 4 submission for a short time after the Pilot 3 clearance is complete.
* Because of its large size, submitting the precompiled version of the WebAssembly transfer through the FDA gateway will require an extra step of downloading a zip archive into the transfer repo.
* Eric is  now testing on Windows 10.
* Eric will debut the app in his talk a posit::conf.


When asked about how he WebAssembly will be perceived within in FDA, Paul replied that it will depend on the use case and who gets involved.


### Docker

Hye Soo has docker installed on her workstation, and will be able work with the Docker version of the Pilot 4 submission when it is ready.

## Expanding the Reach of the R Working Group

* Ning Leng proposed that it is time to expand the reach of the R Submissions working group to include clinicians and non data scientists. 
* She proposed blog posts and perhaps writing an academic paper noting the nature papers on 
  * [Array programming with NumPy](https://www.nature.com/articles/s41586-020-2649-2) and
  * [WebAssembly](https://www.nature.com/articles/d41586-024-00725-1).

**Action**: The group will pursue writing a paper.


## R Licenses

There was a robust discussion about the impediment that the GPL licenses pose to the use of R that begins about 40 minutes into the video.

* JBR noted that company lawyers invariably seem to want to impose worst case measures when first encountering first encountering GPL licenses, and that if they do form an opinion about the limits of the license they are reticent to share their arguments publicly.
* It was suggested that companies avoid using GPL packages 
* It was also noted that R ecosystem is mostly GPL based. An effort to track down the use of GPL licenses in packages and their dependencies included 72% of he CRAN ecosystem.
* One apparent solution is to avoid bundling their code with GPL licensed packages, but to advise users that they should load the required GPL packages themselves.
* The conversation settled on the notion of what is being shared, distinguishing between the code that produces tables and statistical results and code that modifies R in some way to profit from it.
* Several members described how licensing seems to work within their companies.
* An opinion that was offered that GPL 3 IS very "viral" but unless code was linking directly GPL2 is permissive.
* This [Tibco Blog post](https://www.tibco.com/blog/2015/06/15/what-does-microsofts-acquisition-of-revolution-analytics-mean-for-the-r-language/) from 2015 mentions how Microsoft was able to stay on the right side of GPL with its integration of Revolution Analytics code.
* Also see this [InfoWorld Article](https://www.infoworld.com/article/2240474/sql-server-2016-gets-an-r-language-rating.html) by Sedar Yegulap from 2016 which states:

> The easy way to do so and still respect the terms of the GPL is via an “arm’s length” provision. Instead of integrating the R binaries directly into SQL Server, Microsoft could invoke the R software from its own executable as needed, then return results to the host application through a file or a data stream.

### Next Meeting

The next meeting of the R Submissions working group will be on Friday, September 6, 2024 at 9 AM Pacific Time.












