---
title: "Minutes 2022-12-02"
date: 12-02-2022
---

::: {.callout-tip collapse="true"}
## View Attendee List

- Bob Engle (Biogen)
- Brian Sucher (Unknown)
- Christopher Kania (Biogen)
- Dadong Zhang (Illumina)
- Ellis Hughes (GSK)
- Eric Nantz (Eli Lilly)
- Heidi Curinckx (Johnson & Johnson)
- HyeSoo Cho (FDA)
- Jizu Zhi (FDA)
- Joel Laxamana (Roche/Genentech)
- Joseph Rickert (R Consortium)
- Miriam Fossati (Merck)
- Nan Xiao (Merck)
- Ning Leng (Roche/Genentech)
- Paul Schuette (FDA)
- Phil Bowsher (Posit)
- Renping Zhang (Johnson & Johnson)
- Robert Devine (Johnson & Johnson)
- Ryan Johnson (Posit)
- Sam Parmar (Pfizer)
- Stephanie Lussier (Moderna)
- Thomas Neitmann (Roche/Genentech)
- Xin Qiu (Johnson & Johnson)
- Yilong Zhang (Meta)

:::

### Pilot 2
* Ning Leng and Eric Nantz reported that Pilot 2 was submitted on 2022-11-18, upholding the working groups tradition of submitting right before Thanksgiving, and that confirmation was received from the the FDA.
* Paul Schuette explained that since Pilot 2 was  not a production submission it was necessary to make a manual request to receive it. Consequently, his group did not receive it until earlier this wee.
* Heysoo Cho said that she will begin working on the submission next week.
* Eric Nantz offered to be available to help if the FDA had any questions.

### Pilot 3
Joel Laxamana briefly reviewed the preparations his team is making for Pilot 3 and said that the proposal is ready for transmission to the FDA. Paul suggested that the proposal should be sent to everyone in the working group and not just the FDA. Joel agreed to put the proposal in the Submissions WG GitHub repository and send the link to everyone in the working group.

Joel noted that many of the Pilot 3 concepts were taken from the ADRG for Pilot 2 and mentioned that they are checking against the CDISC versions as they build the package.

### Pilot 4
Eric said that he hopes to ramp up Pilot 4 work after the Pilot 2 submission. The simplest plan will be just to containerize the Pilot 2 submission. [Podman](https://podman.io/) is the initial choice for a the container technology.

The group also expressed about aligning the Pilot 4 project with the Validation Hub to stand up a repo of validated packages. This would open up the possibility of hosting the container on the validation repo. The Validation Hub repo for this project is: https://github.com/pharmaR/regulatory-r-repo-wg



### Other Business

JBR asked Ning and Joel for summary paragraphs for Pilot 2 and Pilot 3 for inclusion in end of the year reports on working group status. Ning is working on a blog post about Pilot 2 for inclusion in the R Consortium Blog.

There were no updates available about efforts to make pilot submissions to other regulatory agencies.

The following events were identified as possibilities for delivering presentations:

* The Appsilon Shiny conference: [ShinyConf 2023](https://shinyconf.appsilon.com/) March 15-17 - Ning and Eric are drafting an abstract
* R/Medicine June 8-9
* R/Pharma
* useR! 2023
* Posit::conf
* ASA BioPharma SWE Workshop in September

#### Other future plans:

* Ning noted that she and Yilong have been thinking about a journal submission and have begun writing a draft.
* The group also agreed that they would like to do another R - Adoption Webinar.
* Finally, Eric noted that he would like to rework the Submissions repository site and build it on a Quarto framework.
* **The next meeting of the Submissions WG will be at 10AM PST, Friday 13, 2023.** This is a one week delay to move the meeting beyond the holiday season. 
