---
title: "R Consortium R Submissions Working Group"
params:
  attendees:
    - "Heidi Curinckx"
    - "Bob Engle - BioGen"
    - "Miriam Fossati - Merck"
    - "Christopher Kania - Biogen"
    - "Doug Kelkhoff - Genentech"
    - "Ning Leng - Genentech"
    - "Joseph Rickert - R Consortium"
    - "Michael Rimler - GSK"
    - "Paul Schuette - FDA"
    - "Mike Stackhouse - Atorus"
    - "Ben Staub - GSK"
    - "Adrian Waddell - Roche"
    - "Heng Wang - Genentech"
    - "Peikun Wu - Merck"
    - "Nan Xiao - Merck"
    - "Jiang Xu - FDA"
    - "Renping Zhang - FDA"
    - "Yilong Zhang - Merck"
    - "Jizu Zhi - FDA"
output: 
  distill::distill_article:
    css: css/custom.css
---

## Minutes of 2021-10-01 Meeting prepared by Joseph Rickert

<details>
  <summary>View Attendee List</summary>
  <p>`r glue::glue_collapse(params$attendees, sep="<br>")`</p>
</details>

Joseph Rickert brought the meeting to order and Ning Leng presented an up update on the status of the Pilot 1 project using the slide deck `Leng_Update_10-1-21.pptx` which is available in the [Documents folder](https://github.com/RConsortium/submissions-wg/tree/main/Documents) of submissions-wg GitHub repository.

Paul Schuette suggested that Ning revise the document to refer to "FDA staff" rather than "FDA Reviewer" which provides more latitude for getting FDA help. Paul also noted that although it might be possible it is not likely that the FDA could accomplish the task requested before the R/Pharma conference which begins on November 2. Those present agreed that it is not necessary to tie the completion of the FDA activities to R/Pharma.

After Ning's presentation there was a discussion about suggestions for amending the language to section 4.1.2.10 of the Study Data Technical Performance Guide. Doug Kelkhoff noted that in internal discussions within Genentech the idea was floated that, as written the document may already allow passing R code in tar balls through the FDA gateway. If this were indeed true it would greatly simply R submissions since tar balls are a common method of delivering R code. Jian Xu of the FDA suggest that the way to get an answer to this question is to submit the question to the email address provided on the FDA eCTD webpage: [Submit an eCTD or Standardized Data Sample to the FDA](https://www.fda.gov/drugs/electronic-regulatory-submission-and-review/submit-ectd-or-standardized-data-sample-fda). Joe and Doug took the **action item** to write up the question and submit it.

The group then considered a proposal by Adrian to organize the several GitHub repositories and activities of the Submissions WG using the Teams features of GitHub. The group agreed that this would be a good idea but suggested waiting until after Pilot1 is completed. Adrian will set up a meeting with Joe and Ning to setup the structure.

The video of today's 10-1-21 meeting is available [here](https://rstudio.zoom.us/rec/share/q3guNFXtWp5aKRYAMB1f7CkW2miueFj_uSBuKnvsAksQi9vYvy9IsEAgBgy5eNje.p4Qupsx4WuBHZgQM) passcode: &1b4VEkR

The next meeting of the WG will be at 9AM Pacific Time on Friday November 5, 2021.
