---
title: "R Consortium R Submissions Working Group"
params:
  attendees:
    - "Joseph Rickert - R Consortium"
    - "Adrian Waddell - Roche"
    - "Paul Schuette - FDA"
    - "Bella Feng - EQRX"
    - "Yilong Zhang - Merck"
    - "Doug Kelkhoff - Genentech"
    - "Mike Stackhouse - Atorus Research"
    - "Nan Xiao - Merck"
    - "Ning Leng - Genentech"
    - "Steven Hasendinckx J&J"
    - "Bryant Chen - FDA"
    - "Ojesh Upadhyay - GSK"
output: 
  distill::distill_article:
    css: css/custom.css
---

## Minutes of 2021-03-05 Meeting prepared by Joseph Rickert

<details>
  <summary>View Attendee List</summary>
  <p>`r glue::glue_collapse(params$attendees, sep="<br>")`</p>
</details>

Joseph Rickert opened the meeting at 9AM Pacific Time and pointed to the agenda in the Discussion Section of the GitHub repo.

Agenda:
9:00: Doug Kelkhoff - R Validation Hub infrastructure
9:05: Nan Xiao the R package `pkglite` which packs/unpacks multiple R packages into txt file is going to be used in an upcoming FDA pilot eCTD submission
9:30: Open discussion
We will continue the discussion initiated by Paul Schuette last time about modifying the software section of the [study data technical conformance guide](https://www.fda.gov/industry/fda-resources-data-standards/study-data-standards-resources)

Doug provided an overview of the R Validation Hub protect, pointed out areas of overlap with this working group and welcomed those interested to participate in the Validation Hub effort. Detailed information on the R Validation Hub project which is also organized as an R Consortium working group can be found [here](https://www.pharmar.org/).

Next, Nan Xiao of Merck gave an overview and demo of the R package `pkglite` which is expected to be up on CRAN soon.

The specific aims of the package are: 

* Aim 1: To provide a tool for packing and restoring R packages as plaintext assets that are easy to store, transfer, and review.
* Aim 2: To provide a grammar for specifying the file packing scope that is functional, precise, and extendable.
* Aim 3: To provide a standard for exchanging the packed asset that is unambiguous, human-friendly, and machine-readable.

Nan's presentation can be found in the Document's section of the R Consortium/submissions-wg GitHub repository.

Yilong stated that he hoped that our working group could collaborate on a pilot submission to the FDA. He prepared the following outline to be included in these minutes.

Goal: prepare a open source dummy submission and submit to eCTD portal

The information below is to track potential high level action items. Individual issues can be created to track the progress later.

Data source: [CDISC pilot submission](https://bitbucket.cdisc.org/projects/CED/repos/sdtm-adam-pilot-project/browse)

R program for table listing and figure (TLFs): [program](program: https://github.com/atorus-research/CDISC_pilot_replication)

General action items:  

1. Make sure this use case is following CDISC terms of use
2. Identify TLFs in-scope for submission

Action items for dummy submission package preparation: 

1. Identify point of contact to initiate dummy submission request
2. Prepare analysis results metadata
3. Prepare step-by-step instruction to re-run analysis based on code in program folder and put in ADRG: link
4. Wrap-up submission package

Those present all seemed to be enthusiastic about cooperating on the generating a dummy submission.

Next, followed a lengthy discussion on the required process. Mike Stackhouse suggested that we work with PHUSE to suggest people who may be knowledgeable about past CDISC submissions. Paul Schuette recommended Zak Skrivanek.

Yilong Zhang mentioned that Merck intends to use this package as part of a pilot oncology submission in the near future. Bella mentioned that the FDA Oncology group had specified SAS.

Ning Leng of mentioned that Roche is preparing a rare disease submission for 2022.

Joe Rickert asked the group: assuming the `pkglite` dummy submission is successful, how far the this would advance us towards the ultimate goal of an all R submission.

While everyone was very excited about the `pkglite` all agreed with Doug Kelkhoff's sober assessment that the industry would ultimately want a more "R idiomatic" solution that took advantage of R naming conventions and did not introduce special requirements for R package maintenance. 

Mike Stackhouse noted that a successful `pkglite` submission would break down a significant barrier to R submissions, but that there were other hurdles. Nevertheless, he asserted that it would be a significant advance to be able to say here is "how" you can do an R submission.

It the few minutes that remained, Joe Rickert brought the groups attention to the copy of the word document containing the text of section 4.1.2.10 of the FDA document pertaining to software and asked everyone mark up the document to suggest ideal wording from the industry's point of view.

The group agreed to met next on Friday April 1, at 9AM Pacific time.

The zoom recording of this meeting is available [here](https://zoom.us/rec/share/o-E_jt-wuDDbUCcEhQFwdsE2vZhPlAdcoqo0mgLNmKgqAe3DCDBkxTH_A7eR_MEa.MoCkXvxa5JzE9F2d) (Passcode: `d9N%+JWY`).
