---
title: "R Consortium R Submissions Working Group"
params:
  attendees:
    - "Heidi Curinckx - Janssen"
    - "Miriam Fossati - Merck"
    - "Doug Kelkhoff - Genentech"
    - "Ning Leng - Genentech"
    - "Tadeusz Lewandowski - Roche"
    - "Eli Miller - Atorus"
    - "Joseph Rickert - R Consortium"
    - "Paul Schuette - FDA"
    - "Mike Stackhouse - Atorus"
    - "Adrian Waddell - Roche"
    - "Nan Xiao - Merck"
    - "Yilong Zhang - Merck"
    - "Jizu Zhi - FDA"
output: 
  distill::distill_article:
    css: css/custom.css
---

## Minutes of 2021-08-06 Meeting prepared by Joseph Rickert

<details>
  <summary>View Attendee List</summary>
  <p>`r glue::glue_collapse(params$attendees, sep="<br>")`</p>
</details>

Joseph Rickert brought the meeting to order at 9:04AM. He described how he received an email from the FDA about canceling the ticket for the ESG and asked if this was a problem. The email which was sent by the ESG help desk on 7/22/2021 read:

Ticket 275030: [EXTERNAL] Re: New WebTrader Test Account Registration
Your ticket (275030) has been closed.  You will not be able to update a closed ticket.  If you require additional assistance please send a new email to ESGHelpDesk@fda.hhs.gov.  Below is the history of all actions taken on your ticket (275030).

Note that on Joe received an email regarding ticket 274991
On 7/13/21, at 10:13 am, Sue Kim wrote:

>Hi
Please register online for a TEST ACCOUNT on the FDA Electronic Submissions Gateway (ESG) by following the below instructions:
               1. Go to https://esgtestreg.preprod.fda.gov/
               2. Insert the following registration credentials
                              Username: webtrader
                              Password:
               3. Once you have logged in, follow onscreen registration instructions to complete the registration process.  
NOTE: Both the username and password are case-sensitive and must be entered as shown.
Additional NOTE: When inputting the userID that you will use for your account, please use your email address.
The link below is a Tutorial to help you to complete your account registration.
https://www.fda.gov/ForIndustry/ElectronicSubmissionsGateway /CreateanESGAccount/ucm440674.htm
After you register your account will initially be disabled. The ESG Help Desk will have to activate your account before you can log in and send submissions. We will send an account activation email notification within 48 (3 business days) business hours of registration.  
For more information about the registration process and the FDA ESG in general go to:  http://www.fda.gov/ForIndustry /ElectronicSubmissionsGateway/ and https://www.fda.gov/industry/create-esg-account/setting- webtrader-account-checklist
Thank you
Sue Kim
Joe then asked Ning Leng and Yilong Zhang to summarize the work they have been doing to prepare the pilot submission and describe the structure of the documents they placed in the [WG's GitHub repository](https://github.com/RConsortium/submissions-wg).

Ning set the goal of the meeting to get alignment on the high level tasks and recruit people to help with the work. She began with an overview of the documents in the new repository https://github.com/RConsortium/r-submission-site

Some highlights of Ning's overview:   

* All work will be done in the open with the R Consortium being the sponsor for the pilot submissions.
* The submission package will not favor any one company. R packages used should be either open source or packages developed by multiple companies.
* Three different pilots are planned, each one being more ambitious than the previous.
* Ning and Yilong estimate three months to do the submission
* We need to set up the account with the FDA
* There is a [project board](https://github.com/RConsortium/submissions-wg/projects/1) summarizing the tasks.
* An [R Markdown document](https://github.com/RConsortium/submissions-wg/blob/main/project-plan.Rmd) describes the project
* It is envisioned that the [r-submission-site](https://github.com/RConsortium/r-submission-site) will be public facing and user friendly

There was a discussion about how much documentation needs to go into the phase 1 Pilot. Yilong noted that the a CSR and other materials have already been submitted in the CDISC pilot and since we are only submitting R versions of some of the SAS tables in the CDISC pilot we can refer to those.

Some of the CDISC documents have already been placed into the [Pilot 1 package](https://github.com/RConsortium/submissions-wg/tree/main/submission-package).

Adrian asked for clarification about the differences between Pilot 1 and Pilot 2. Ning said they were thinking to include and analysis package in Pilot 2. Adrian also suggested including reviewer aids in Pilots 2 and 3, including Shiny apps and the like.

The conversation shifted to what was required to get the FDA account set up.
Paul suggested consulting with Ethan's group. Ning took the **Action Item** to ask the Roche submissions team what needs to be done.

Adrian suggested that we augment the project board to reflect *To Do*, *In Progress*, *Done*

Joe granted maintainer privileges for the submissions-wg repo to the following members of the WG: Eli Miller, Yilong Zhang, Eric Nantz, Ning Leng, Adrian Waddell.

Adrian then set up the Kanban board in real time.
Ning and Yilong will populate the Kanban with the tasks they defined.

We are not able to use the credentials above to access the FDA account. Sorting this out was assigned as a task on the Kanban board.

The second half of the video of the meeting includes Adrian showing how to use the projects board.

The [zoom recording](https://rstudio.zoom.us/rec/share/VcDK4VNm_pCqiGLdZG3bwnmgRTNGnAeRz0cz4zfJa0B-qRdGTUmIoUUlQ3SJCF3l.pQth2jLijLpsFsXz) is available. Passcode: `GV0v+#$V`

The next meething is scheduled for 9AM Pacific Time on Friday, September 3, 2021.