---
title: "Q & A"
---

## About R based regulatory submission 

1. How to submit readable code in R to submit to the FDA.
  - Readable code can be submitted as .r files, according to the [R consortium R submission working group pilot 1](https://github.com/RConsortium/submissions-pilot1-to-fda).
  - Analytical codes using functions in open-sourced or proprietary packages are considered readable, as long as the proprietary R packages are submitted in the way as mentioned below.


2. How to submit proprietary R packages to FDA.
  - Proprietary packages cannot be submitted as a compressed file through the eCTD gateway.

  - However, proprietary R packages can be converted to plain .txt file by [pkglite](https://merck.github.io/pkglite/) then submitted through the eCTD gateway. FDA reviewers can use the same package to convert the txt file back to R package. An example can be found in the [R consortium R submission working group pilot 1](https://github.com/RConsortium/submissions-pilot1-to-fda).

3. What if open sourced R packages are used?
  - No need to submit source code of open source packages.
  - In adrg/programtoc, include package version, its dependency packages and their versions
  - In analytical code, include appropriate library() calls. 


4. If R is used, what is needed for the ADRG?
 - If you use R it is recommended to have a section in the ADRG/programtoc that provides the FDA with: 
    - R version
    - Package dependencies and their versions
    - Instructions to convert proprietary R package txt files back to the natural format (if proprietary R packages are submitted)



## About the R consortium R submission working group

1. Who can join the working group? How can I get involved?
  - anyone can join the working group. The working group meets monthly on Friday. If you are interested in joining the monthly meetings, please contact Joe Rickert at joseph.rickert@rstudio.com. 
  - You can also monitor our [issue board](https://github.com/RConsortium/submissions-wg/issues). Any contribution/feedback are more than welcome!